/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripTripIdRouteImport } from './routes/trip.$tripId'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdRoute = TripTripIdRouteImport.update({
  id: '/trip/$tripId',
  path: '/trip/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ProfileRoute,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/trip/$tripId': typeof TripTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/trip/$tripId': typeof TripTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/trip/$tripId': typeof TripTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chats'
    | '/create'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/settings'
    | '/chat/$chatId'
    | '/profile/$userId'
    | '/trip/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chats'
    | '/create'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/settings'
    | '/chat/$chatId'
    | '/profile/$userId'
    | '/trip/$tripId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chats'
    | '/create'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/settings'
    | '/chat/$chatId'
    | '/profile/$userId'
    | '/trip/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatsRoute: typeof ChatsRoute
  CreateRoute: typeof CreateRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
  TripTripIdRoute: typeof TripTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId': {
      id: '/trip/$tripId'
      path: '/trip/$tripId'
      fullPath: '/trip/$tripId'
      preLoaderRoute: typeof TripTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileUserIdRoute: ProfileUserIdRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatsRoute: ChatsRoute,
  CreateRoute: CreateRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  ChatChatIdRoute: ChatChatIdRoute,
  TripTripIdRoute: TripTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
